# This configuration is shared between the OAuth Service and the SPI operator

sharedSecret: <SHARED_SECRET_VALUE>
serviceProviders:
  - type: GitHub
    clientId: "123"
    clientSecret: "42"
  - type: Quay
    clientId: "456"
    clientSecret: "54"
baseUrl: http://<OAUTH_HOST_VALUE>
