# This configuration is shared between the OAuth Service and the SPI operator

serviceProviders:
- type: GitHub
  clientId: "38eadf05310178513aed"
  clientSecret: "1f73dd86638b9bc09f6e7b364d6f9bbad949cdaa"
  redirectUrl: https://localhost:8080/github/callback
